apiVersion: v1
kind: Service
metadata:
  name: ai-ambitions-frontend
  namespace: ai-ambitions
spec:
  type: ClusterIP
  selector:
    app: ai-ambitions-frontend
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
