apiVersion: v1
kind: Service
metadata:
  name: ai-ambitions
  namespace: ai-ambitions
spec:
  type: ClusterIP
  selector:
    app: ai-ambitions
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
